export interface StateOrUT {
  name: string;
  type: "state" | "union_territory";
  cities: string[];
}

export const INDIA_STATES_AND_UTS: StateOrUT[] = [
  // 28 STATES
  {
    name: "Andhra Pradesh",
    type: "state",
    cities: [
      "Visakhapatnam",
      "Vijayawada",
      "Guntur",
      "Tirupati",
      "Nellore",
      "Kurnool",
      "Rajahmundry",
      "Kakinada",
      "Kadapa",
      "Anantapur",
      "Ongole",
      "Eluru",
    ],
  },
  {
    name: "Arunachal Pradesh",
    type: "state",
    cities: [
      "Itanagar",
      "Naharlagun",
      "Tawang",
      "Pasighat",
      "Ziro",
      "Bomdila",
      "Namsai",
      "Tezu",
    ],
  },
  {
    name: "Assam",
    type: "state",
    cities: [
      "Guwahati",
      "Silchar",
      "Dibrugarh",
      "Jorhat",
      "Nagaon",
      "Tinsukia",
      "Tezpur",
      "Sivasagar",
      "Bongaigaon",
      "Diphu",
    ],
  },
  {
    name: "Bihar",
    type: "state",
    cities: [
      "Patna",
      "Gaya",
      "Muzaffarpur",
      "Bhagalpur",
      "Darbhanga",
      "Purnia",
      "Bihar Sharif",
      "Arrah",
      "Begusarai",
      "Katihar",
      "Munger",
      "Chapra",
    ],
  },
  {
    name: "Chhattisgarh",
    type: "state",
    cities: [
      "Raipur",
      "Bhilai",
      "Bilaspur",
      "Korba",
      "Durg",
      "Rajnandgaon",
      "Jagdalpur",
      "Raigarh",
      "Ambikapur",
      "Dhamtari",
    ],
  },
  {
    name: "Goa",
    type: "state",
    cities: [
      "Panaji",
      "Margao",
      "Vasco da Gama",
      "Mapusa",
      "Ponda",
      "Bicholim",
      "Canacona",
    ],
  },
  {
    name: "Gujarat",
    type: "state",
    cities: [
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rajkot",
      "Gandhinagar",
      "Bhavnagar",
      "Jamnagar",
      "Junagadh",
      "Anand",
      "Bharuch",
      "Vapi",
      "Nadiad",
      "Mehsana",
      "Morbi",
      "Porbandar",
    ],
  },
  {
    name: "Haryana",
    type: "state",
    cities: [
      "Gurugram",
      "Faridabad",
      "Panipat",
      "Ambala",
      "Hisar",
      "Karnal",
      "Rohtak",
      "Sonipat",
      "Yamunanagar",
      "Panchkula",
      "Kurukshetra",
      "Rewari",
      "Sirsa",
      "Bhiwani",
    ],
  },
  {
    name: "Himachal Pradesh",
    type: "state",
    cities: [
      "Shimla",
      "Dharamshala",
      "Solan",
      "Mandi",
      "Kullu",
      "Manali",
      "Hamirpur",
      "Una",
      "Bilaspur",
      "Chamba",
      "Nahan",
      "Baddi",
    ],
  },
  {
    name: "Jharkhand",
    type: "state",
    cities: [
      "Ranchi",
      "Jamshedpur",
      "Dhanbad",
      "Bokaro",
      "Deoghar",
      "Hazaribagh",
      "Giridih",
      "Ramgarh",
      "Phusro",
      "Medininagar",
    ],
  },
  {
    name: "Karnataka",
    type: "state",
    cities: [
      "Bengaluru",
      "Mysuru",
      "Mangaluru",
      "Hubballi",
      "Dharwad",
      "Belagavi",
      "Kalaburagi",
      "Davanagere",
      "Ballari",
      "Shivamogga",
      "Tumakuru",
      "Udupi",
      "Hassan",
      "Vijayapura",
    ],
  },
  {
    name: "Kerala",
    type: "state",
    cities: [
      "Thiruvananthapuram",
      "Kochi",
      "Kozhikode",
      "Kollam",
      "Thrissur",
      "Kannur",
      "Alappuzha",
      "Kottayam",
      "Palakkad",
      "Malappuram",
      "Kasaragod",
      "Pathanamthitta",
    ],
  },
  {
    name: "Madhya Pradesh",
    type: "state",
    cities: [
      "Indore",
      "Bhopal",
      "Jabalpur",
      "Gwalior",
      "Ujjain",
      "Sagar",
      "Rewa",
      "Satna",
      "Ratlam",
      "Dewas",
      "Khandwa",
      "Burhanpur",
      "Chhindwara",
      "Guna",
    ],
  },
  {
    name: "Maharashtra",
    type: "state",
    cities: [
      "Mumbai",
      "Pune",
      "Nagpur",
      "Nashik",
      "Thane",
      "Navi Mumbai",
      "Chhatrapati Sambhajinagar",
      "Kolhapur",
      "Solapur",
      "Amravati",
      "Nanded",
      "Sangli",
      "Satara",
      "Jalgaon",
      "Akola",
      "Latur",
    ],
  },
  {
    name: "Manipur",
    type: "state",
    cities: [
      "Imphal",
      "Thoubal",
      "Bishnupur",
      "Churachandpur",
      "Ukhrul",
      "Senapati",
      "Tamenglong",
    ],
  },
  {
    name: "Meghalaya",
    type: "state",
    cities: [
      "Shillong",
      "Tura",
      "Jowai",
      "Nongpoh",
      "Williamnagar",
      "Baghmara",
    ],
  },
  {
    name: "Mizoram",
    type: "state",
    cities: [
      "Aizawl",
      "Lunglei",
      "Champhai",
      "Kolasib",
      "Serchhip",
      "Mamit",
      "Saiha",
    ],
  },
  {
    name: "Nagaland",
    type: "state",
    cities: [
      "Kohima",
      "Dimapur",
      "Mokokchung",
      "Tuensang",
      "Wokha",
      "Mon",
      "Zunheboto",
    ],
  },
  {
    name: "Odisha",
    type: "state",
    cities: [
      "Bhubaneswar",
      "Cuttack",
      "Rourkela",
      "Berhampur",
      "Sambalpur",
      "Puri",
      "Balasore",
      "Baripada",
      "Bhadrak",
      "Jharsuguda",
      "Angul",
      "Jeypore",
    ],
  },
  {
    name: "Punjab",
    type: "state",
    cities: [
      "Ludhiana",
      "Amritsar",
      "Jalandhar",
      "Patiala",
      "Bathinda",
      "Mohali",
      "Pathankot",
      "Hoshiarpur",
      "Moga",
      "Batala",
      "Firozpur",
      "Abohar",
      "Khanna",
      "Kapurthala",
    ],
  },
  {
    name: "Rajasthan",
    type: "state",
    cities: [
      "Jaipur",
      "Jodhpur",
      "Udaipur",
      "Kota",
      "Ajmer",
      "Bikaner",
      "Alwar",
      "Bharatpur",
      "Sikar",
      "Sri Ganganagar",
      "Bhilwara",
      "Pali",
      "Tonk",
      "Chittorgarh",
      "Barmer",
      "Jaisalmer",
    ],
  },
  {
    name: "Sikkim",
    type: "state",
    cities: [
      "Gangtok",
      "Namchi",
      "Gyalshing",
      "Mangan",
      "Singtam",
      "Rangpo",
    ],
  },
  {
    name: "Tamil Nadu",
    type: "state",
    cities: [
      "Chennai",
      "Coimbatore",
      "Madurai",
      "Tiruchirappalli",
      "Salem",
      "Tiruppur",
      "Erode",
      "Vellore",
      "Thoothukudi",
      "Tirunelveli",
      "Thanjavur",
      "Dindigul",
      "Hosur",
      "Nagercoil",
      "Kanchipuram",
    ],
  },
  {
    name: "Telangana",
    type: "state",
    cities: [
      "Hyderabad",
      "Warangal",
      "Nizamabad",
      "Karimnagar",
      "Khammam",
      "Ramagundam",
      "Mahbubnagar",
      "Nalgonda",
      "Adilabad",
      "Suryapet",
      "Siddipet",
    ],
  },
  {
    name: "Tripura",
    type: "state",
    cities: [
      "Agartala",
      "Udaipur",
      "Dharmanagar",
      "Kailasahar",
      "Belonia",
      "Ambassa",
      "Kumarghat",
    ],
  },
  {
    name: "Uttar Pradesh",
    type: "state",
    cities: [
      "Lucknow",
      "Kanpur",
      "Ghaziabad",
      "Agra",
      "Varanasi",
      "Prayagraj",
      "Meerut",
      "Noida",
      "Gorakhpur",
      "Bareilly",
      "Moradabad",
      "Aligarh",
      "Saharanpur",
      "Mathura",
      "Firozabad",
      "Jhansi",
      "Muzaffarnagar",
      "Ayodhya",
      "Rampur",
      "Shahjahanpur",
    ],
  },
  {
    name: "Uttarakhand",
    type: "state",
    cities: [
      "Dehradun",
      "Haridwar",
      "Haldwani",
      "Rishikesh",
      "Roorkee",
      "Rudrapur",
      "Kashipur",
      "Nainital",
      "Almora",
      "Pithoragarh",
      "Srinagar",
      "Mussoorie",
    ],
  },
  {
    name: "West Bengal",
    type: "state",
    cities: [
      "Kolkata",
      "Howrah",
      "Durgapur",
      "Asansol",
      "Siliguri",
      "Darjeeling",
      "Kharagpur",
      "Haldia",
      "Malda",
      "Berhampore",
      "Bardhaman",
      "Raiganj",
      "Jalpaiguri",
    ],
  },

  // 8 UNION TERRITORIES
  {
    name: "Andaman & Nicobar Islands",
    type: "union_territory",
    cities: ["Port Blair", "Diglipur", "Mayabunder", "Rangat", "Hut Bay"],
  },
  {
    name: "Chandigarh",
    type: "union_territory",
    cities: ["Chandigarh"],
  },
  {
    name: "Dadra & Nagar Haveli and Daman & Diu",
    type: "union_territory",
    cities: ["Silvassa", "Daman", "Diu"],
  },
  {
    name: "Delhi (NCT)",
    type: "union_territory",
    cities: [
      "New Delhi",
      "Delhi",
      "Dwarka",
      "Rohini",
      "Saket",
      "Karol Bagh",
      "Lajpat Nagar",
      "Janakpuri",
      "Shahdara",
      "Vasant Kunj",
    ],
  },
  {
    name: "Jammu & Kashmir",
    type: "union_territory",
    cities: [
      "Srinagar",
      "Jammu",
      "Anantnag",
      "Baramulla",
      "Kathua",
      "Udhampur",
      "Sopore",
      "Kupwara",
      "Pulwama",
      "Rajouri",
      "Poonch",
    ],
  },
  {
    name: "Ladakh",
    type: "union_territory",
    cities: ["Leh", "Kargil", "Diskit", "Padum"],
  },
  {
    name: "Lakshadweep",
    type: "union_territory",
    cities: ["Kavaratti", "Agatti", "Amini", "Andrott", "Kalpeni", "Minicoy"],
  },
  {
    name: "Puducherry",
    type: "union_territory",
    cities: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
  },
];

/**
 * Common high-converting customer search query patterns for any city
 */
export const SEARCH_INTENT_TEMPLATES = [
  "best digital marketing agency in {city}",
  "digital marketing agency near me in {city}",
  "top SEO company in {city}",
  "Google Maps ranking agency {city}",
  "local SEO services in {city}",
  "best digital marketing company in {city}",
  "Google Ads PPC management {city}",
  "website development company in {city}",
  "social media marketing agency in {city}",
  "lead generation company {city}",
  "performance marketing agency in {city}",
  "AI search optimization (GEO) {city}",
];

/**
 * Returns a flat list of all unique cities across India
 */
export function getAllIndianCities(): string[] {
  const set = new Set<string>();
  for (const item of INDIA_STATES_AND_UTS) {
    for (const city of item.cities) {
      set.add(city);
    }
  }
  return Array.from(set);
}

/**
 * Returns key customer search keywords for a specific city
 */
export function getCityKeywords(city: string, stateName?: string): string[] {
  const base = SEARCH_INTENT_TEMPLATES.map((tpl) => tpl.replace("{city}", city));
  if (stateName) {
    base.push(`digital marketing agency in ${city} ${stateName}`);
    base.push(`best SEO agency ${city} ${stateName}`);
  }
  return base;
}

/**
 * High-intent search terms targeting "near me", high-intent business inquiries, and tier-1/2 Indian hubs
 */
export const CORE_CUSTOMER_SEARCH_KEYWORDS: string[] = [
  // Near Me Intent (Extremely high conversion)
  "best digital marketing agency near me",
  "digital marketing agency near me",
  "digital marketing company near me",
  "best SEO company near me",
  "SEO agency near me",
  "local SEO agency near me",
  "Google Maps ranking agency near me",
  "website development company near me",
  "Google Ads PPC agency near me",
  "social media marketing agency near me",
  "performance marketing agency near me",
  "lead generation agency near me",

  // Delhi NCR & Primary Headquarter Region
  "best digital marketing agency in Ghaziabad",
  "digital marketing agency in Ghaziabad - Delhi NCR",
  "best digital marketing company in Ghaziabad",
  "SEO agency Ghaziabad",
  "Google Maps Top 3 agency Ghaziabad",
  "digital marketing agency Noida",
  "digital marketing agency Greater Noida",
  "digital marketing company Gurgaon Gurugram",
  "digital marketing agency Delhi",
  "digital marketing agency Faridabad",
  "digital marketing agency Crossings Republik",
  "digital marketing agency Indirapuram",
  "digital marketing company Raj Nagar Ghaziabad",

  // Top Indian Metros & Tech Hubs
  "best digital marketing agency in Mumbai",
  "digital marketing agency in Bengaluru Bangalore",
  "best digital marketing company in Hyderabad",
  "digital marketing agency in Pune Maharashtra",
  "top digital marketing agency in Ahmedabad Gujarat",
  "digital marketing company in Chennai Tamil Nadu",
  "best digital marketing agency in Kolkata",
  "digital marketing agency in Jaipur Rajasthan",
  "digital marketing company in Lucknow Uttar Pradesh",
  "best digital marketing company in Chandigarh",
  "digital marketing agency in Indore Madhya Pradesh",
  "digital marketing company in Kochi Kerala",
  "digital marketing agency in Patna Bihar",
  "digital marketing services in Surat",
  "digital marketing agency in Kanpur",
  "digital marketing agency in Nagpur",
  "digital marketing company in Visakhapatnam",
  "digital marketing agency in Bhubaneswar",
  "digital marketing agency in Ludhiana",
  "digital marketing company in Dehradun",

  // Global & USA Target Export Markets
  "digital marketing agency for US businesses",
  "digital marketing agency USA",
  "digital marketing agency New York",
  "digital marketing agency California",
  "SEO and web development Texas",
  "offshore digital marketing agency India",
  "Digital FX",
];

/**
 * Schema.org areaServed list covering all 28 States, 8 UTs, and major urban districts
 */
export const ALL_INDIA_AREA_SERVED_SCHEMA = [
  { "@type": "Country", name: "India" },
  { "@type": "Country", name: "United States" },
  ...INDIA_STATES_AND_UTS.map((item) => ({
    "@type": item.type === "state" ? "State" : "AdministrativeArea",
    name: item.name,
  })),
  // Add primary high-volume commercial centers as City entities
  { "@type": "City", name: "Ghaziabad" },
  { "@type": "City", name: "Noida" },
  { "@type": "City", name: "New Delhi" },
  { "@type": "City", name: "Gurugram" },
  { "@type": "City", name: "Faridabad" },
  { "@type": "City", name: "Mumbai" },
  { "@type": "City", name: "Pune" },
  { "@type": "City", name: "Bengaluru" },
  { "@type": "City", name: "Hyderabad" },
  { "@type": "City", name: "Ahmedabad" },
  { "@type": "City", name: "Chennai" },
  { "@type": "City", name: "Kolkata" },
  { "@type": "City", name: "Jaipur" },
  { "@type": "City", name: "Lucknow" },
  { "@type": "City", name: "Kanpur" },
  { "@type": "City", name: "Indore" },
  { "@type": "City", name: "Chandigarh" },
  { "@type": "City", name: "Kochi" },
  { "@type": "City", name: "Patna" },
  { "@type": "City", name: "Surat" },
  { "@type": "City", name: "Nagpur" },
  { "@type": "City", name: "Visakhapatnam" },
  { "@type": "City", name: "Bhubaneswar" },
  { "@type": "City", name: "Ludhiana" },
  { "@type": "City", name: "Dehradun" },
  { "@type": "City", name: "Bhopal" },
  { "@type": "City", name: "Vadodara" },
  { "@type": "City", name: "Coimbatore" },
  { "@type": "City", name: "Varanasi" },
  { "@type": "City", name: "Agra" },
  { "@type": "City", name: "Prayagraj" },
  { "@type": "City", name: "Meerut" },
];
