import {
  Plan,
  Business,
  WhatsAppAccount,
  Lead,
  Customer,
  Conversation,
  ChatMessage,
  MessageTemplate,
  Automation,
  Campaign,
  Followup,
  TeamMember,
  UsageRecord,
  Invoice,
  PaymentTransaction,
  AuditLog,
  SupportTicket,
  SaasUser,
} from "./types";

export const SAAS_PLANS: Plan[] = [
  {
    id: "plan_starter",
    name: "Starter",
    tier: "starter",
    priceMonthly: 1999,
    priceAnnual: 19990,
    description: "Ideal for small local clinics, retail shops, and boutique firms getting started with WhatsApp.",
    limits: {
      users: 2,
      contacts: 1000,
      automations: 3,
      monthlyMessages: 2500,
      campaignsPerMonth: 2,
      whatsappNumbers: 1,
      storageMb: 500,
    },
    features: [
      "1 Official WhatsApp Business API Number",
      "2 Agent Inbox Seats",
      "3 Live Workflow Automations",
      "Up to 1,000 Contacts CRM",
      "Standard WhatsApp Message Templates",
      "Basic Analytics & CSV Export",
    ],
    isActive: true,
  },
  {
    id: "plan_growth",
    name: "Growth",
    tier: "growth",
    priceMonthly: 4999,
    priceAnnual: 49990,
    description: "Best for growing businesses scaling lead generation and customer support via WhatsApp.",
    limits: {
      users: 5,
      contacts: 5000,
      automations: 10,
      monthlyMessages: 15000,
      campaignsPerMonth: 10,
      whatsappNumbers: 1,
      storageMb: 2000,
    },
    features: [
      "1 Official WhatsApp Business API Number",
      "5 Team Agent Seats with RBAC",
      "10 Advanced Automations & Branching",
      "5,000 Contacts CRM with Tags & Filters",
      "Scheduled Broadcasts & Drip Campaigns",
      "Live Kanban Lead Pipeline",
      "Webhook & Zapier Integration",
    ],
    isActive: true,
  },
  {
    id: "plan_business",
    name: "Business Pro",
    tier: "business",
    priceMonthly: 9999,
    priceAnnual: 99990,
    description: "Comprehensive multi-agent WhatsApp CRM and automation suite for high-volume sales teams.",
    limits: {
      users: 15,
      contacts: 25000,
      automations: 35,
      monthlyMessages: 60000,
      campaignsPerMonth: 30,
      whatsappNumbers: 2,
      storageMb: 10000,
    },
    features: [
      "2 WhatsApp Business Numbers",
      "15 Agent Seats with Advanced Routing",
      "35 Dynamic Automations & Chatbots",
      "25,000 Contact Database",
      "Unlimited Broadcast Campaigns",
      "Full Webhook Engine & Custom Variables",
      "Priority SLA & Dedicated Support Desk",
    ],
    isActive: true,
  },
  {
    id: "plan_enterprise",
    name: "Enterprise",
    tier: "enterprise",
    priceMonthly: 24999,
    priceAnnual: 249990,
    description: "Unlimited scale, multi-branch routing, and custom API throughput for enterprise operations.",
    limits: {
      users: 100,
      contacts: 200000,
      automations: 150,
      monthlyMessages: 250000,
      campaignsPerMonth: 100,
      whatsappNumbers: 5,
      storageMb: 50000,
    },
    features: [
      "Up to 5 WhatsApp Business Numbers",
      "Unlimited Team Members & Role Hierarchy",
      "Unlimited Chatbots & Visual Automations",
      "Tier 4 High-Throughput Meta Sending (80 msg/sec)",
      "Dedicated Database & Custom Webhooks",
      "Dedicated Account Strategist & 99.9% Uptime",
    ],
    isActive: true,
  },
];

export const DEMO_USERS: SaasUser[] = [
  {
    id: "user_super_admin",
    email: "yshashank513@gmail.com",
    name: "Shashank Yadav",
    role: "super_admin",
    createdAt: "2026-01-10T10:00:00Z",
    lastLoginAt: "2026-10-04T12:00:00Z",
  },
  {
    id: "user_apex_owner",
    email: "dr.arun@apexhealthcare.in",
    name: "Dr. Arun Mehra",
    role: "owner",
    businessId: "biz_apex_health",
    phone: "+91 98101 23456",
    createdAt: "2026-02-15T11:00:00Z",
    lastLoginAt: "2026-10-04T10:30:00Z",
  },
  {
    id: "user_apex_agent",
    email: "priya.frontdesk@apexhealthcare.in",
    name: "Priya Sharma (Patient Desk)",
    role: "agent",
    businessId: "biz_apex_health",
    phone: "+91 98101 77889",
    createdAt: "2026-03-01T09:00:00Z",
    lastLoginAt: "2026-10-04T11:15:00Z",
  },
  {
    id: "user_urbannest_owner",
    email: "vikram@urbannestrealty.com",
    name: "Vikram Singhania",
    role: "owner",
    businessId: "biz_urbannest",
    phone: "+91 98711 55443",
    createdAt: "2026-02-20T14:00:00Z",
    lastLoginAt: "2026-10-04T09:45:00Z",
  },
  {
    id: "user_nexora_owner",
    email: "kavita@nexoratech.io",
    name: "Kavita Rao",
    role: "owner",
    businessId: "biz_nexora",
    phone: "+91 99880 11223",
    createdAt: "2026-03-05T10:00:00Z",
    lastLoginAt: "2026-10-03T16:20:00Z",
  },
  {
    id: "user_spicecraft_owner",
    email: "manish@spicecraftdining.com",
    name: "Manish Kapoor",
    role: "owner",
    businessId: "biz_spicecraft",
    phone: "+91 98112 99001",
    createdAt: "2026-03-12T12:00:00Z",
    lastLoginAt: "2026-10-04T08:10:00Z",
  },
  {
    id: "user_velocita_owner",
    email: "rajat@velocitamotors.in",
    name: "Rajat Verma",
    role: "owner",
    businessId: "biz_velocita",
    phone: "+91 98990 44556",
    createdAt: "2026-03-18T15:00:00Z",
    lastLoginAt: "2026-10-04T11:50:00Z",
  },
];

export const DEMO_BUSINESSES: Business[] = [
  {
    id: "biz_apex_health",
    name: "Apex Super-Speciality Hospital",
    slug: "apex-healthcare",
    ownerName: "Dr. Arun Mehra",
    ownerEmail: "dr.arun@apexhealthcare.in",
    ownerPhone: "+91 98101 23456",
    industry: "Healthcare & Multispeciality Clinics",
    website: "https://apexhealthcare.in",
    address: "Plot 12, Sector 14, Kaushambi",
    city: "Ghaziabad",
    state: "Uttar Pradesh",
    country: "India",
    googleBusinessUrl: "https://maps.google.com/?cid=123456789",
    status: "active",
    planId: "plan_enterprise",
    planTier: "enterprise",
    subscriptionStatus: "active",
    whatsappConnected: true,
    whatsappNumber: "+91 98101 23456",
    createdAt: "2026-02-15T11:00:00Z",
    lastActivityAt: "2026-10-04T12:35:00Z",
  },
  {
    id: "biz_urbannest",
    name: "UrbanNest Luxury Real Estate",
    slug: "urbannest-realty",
    ownerName: "Vikram Singhania",
    ownerEmail: "vikram@urbannestrealty.com",
    ownerPhone: "+91 98711 55443",
    industry: "Real Estate & Developers",
    website: "https://urbannestrealty.com",
    address: "Tower B, Level 9, Logix Cyber Park, Sector 62",
    city: "Noida",
    state: "Uttar Pradesh",
    country: "India",
    googleBusinessUrl: "https://maps.google.com/?cid=987654321",
    status: "active",
    planId: "plan_business",
    planTier: "business",
    subscriptionStatus: "active",
    whatsappConnected: true,
    whatsappNumber: "+91 98711 55443",
    createdAt: "2026-02-20T14:00:00Z",
    lastActivityAt: "2026-10-04T11:45:00Z",
  },
  {
    id: "biz_nexora",
    name: "Nexora Cloud Technologies",
    slug: "nexora-tech",
    ownerName: "Kavita Rao",
    ownerEmail: "kavita@nexoratech.io",
    ownerPhone: "+91 99880 11223",
    industry: "SaaS & Enterprise IT",
    website: "https://nexoratech.io",
    address: "DLF Cyber City, Building 10, Phase 2",
    city: "Gurugram",
    state: "Haryana",
    country: "India",
    googleBusinessUrl: "https://maps.google.com/?cid=554433221",
    status: "active",
    planId: "plan_growth",
    planTier: "growth",
    subscriptionStatus: "active",
    whatsappConnected: true,
    whatsappNumber: "+91 99880 11223",
    createdAt: "2026-03-05T10:00:00Z",
    lastActivityAt: "2026-10-04T10:15:00Z",
  },
  {
    id: "biz_spicecraft",
    name: "SpiceCraft Gourmet Dining Group",
    slug: "spicecraft-dining",
    ownerName: "Manish Kapoor",
    ownerEmail: "manish@spicecraftdining.com",
    ownerPhone: "+91 98112 99001",
    industry: "Restaurants & Hospitality",
    website: "https://spicecraftdining.com",
    address: "Block M, Outer Circle, Connaught Place",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    googleBusinessUrl: "https://maps.google.com/?cid=112233445",
    status: "trial",
    planId: "plan_starter",
    planTier: "starter",
    trialEndsAt: "2026-10-18T23:59:59Z",
    subscriptionStatus: "trialing",
    whatsappConnected: true,
    whatsappNumber: "+91 98112 99001",
    createdAt: "2026-03-12T12:00:00Z",
    lastActivityAt: "2026-10-04T08:50:00Z",
  },
  {
    id: "biz_velocita",
    name: "Velocita Premium Motors",
    slug: "velocita-motors",
    ownerName: "Rajat Verma",
    ownerEmail: "rajat@velocitamotors.in",
    ownerPhone: "+91 98990 44556",
    industry: "Automotive & Luxury Dealerships",
    website: "https://velocitamotors.in",
    address: "Knowledge Park III, Pari Chowk Corridor",
    city: "Greater Noida",
    state: "Uttar Pradesh",
    country: "India",
    googleBusinessUrl: "https://maps.google.com/?cid=998877665",
    status: "active",
    planId: "plan_business",
    planTier: "business",
    subscriptionStatus: "active",
    whatsappConnected: true,
    whatsappNumber: "+91 98990 44556",
    createdAt: "2026-03-18T15:00:00Z",
    lastActivityAt: "2026-10-04T12:05:00Z",
  },
];

export const DEMO_WHATSAPP_ACCOUNTS: WhatsAppAccount[] = [
  {
    id: "waba_apex",
    businessId: "biz_apex_health",
    businessName: "Apex Super-Speciality Hospital",
    wabaId: "109823471829304",
    phoneNumberId: "108723940182741",
    displayPhoneNumber: "+91 98101 23456",
    verifiedName: "Apex Healthcare Official",
    qualityRating: "GREEN",
    status: "CONNECTED",
    webhookStatus: "VERIFIED",
    lastSyncAt: "2026-10-04T12:30:00Z",
    messagingLimitTier: "TIER_100K",
    dailyMessagesSentToday: 1420,
    dailyMessagesLimit: 100000,
  },
  {
    id: "waba_urbannest",
    businessId: "biz_urbannest",
    businessName: "UrbanNest Luxury Real Estate",
    wabaId: "209847120934812",
    phoneNumberId: "208734918203948",
    displayPhoneNumber: "+91 98711 55443",
    verifiedName: "UrbanNest Properties",
    qualityRating: "GREEN",
    status: "CONNECTED",
    webhookStatus: "VERIFIED",
    lastSyncAt: "2026-10-04T11:40:00Z",
    messagingLimitTier: "TIER_10K",
    dailyMessagesSentToday: 680,
    dailyMessagesLimit: 10000,
  },
  {
    id: "waba_nexora",
    businessId: "biz_nexora",
    businessName: "Nexora Cloud Technologies",
    wabaId: "309858291029384",
    phoneNumberId: "308745029384756",
    displayPhoneNumber: "+91 99880 11223",
    verifiedName: "Nexora Tech Desk",
    qualityRating: "GREEN",
    status: "CONNECTED",
    webhookStatus: "VERIFIED",
    lastSyncAt: "2026-10-04T10:10:00Z",
    messagingLimitTier: "TIER_1K",
    dailyMessagesSentToday: 215,
    dailyMessagesLimit: 1000,
  },
  {
    id: "waba_spicecraft",
    businessId: "biz_spicecraft",
    businessName: "SpiceCraft Gourmet Dining Group",
    wabaId: "409869302194857",
    phoneNumberId: "408756130495867",
    displayPhoneNumber: "+91 98112 99001",
    verifiedName: "SpiceCraft Table Reservations",
    qualityRating: "YELLOW",
    status: "CONNECTED",
    webhookStatus: "VERIFIED",
    lastSyncAt: "2026-10-04T08:45:00Z",
    messagingLimitTier: "TIER_250",
    dailyMessagesSentToday: 85,
    dailyMessagesLimit: 250,
  },
  {
    id: "waba_velocita",
    businessId: "biz_velocita",
    businessName: "Velocita Premium Motors",
    wabaId: "509870413205968",
    phoneNumberId: "508767241506978",
    displayPhoneNumber: "+91 98990 44556",
    verifiedName: "Velocita Motors VIP Desk",
    qualityRating: "GREEN",
    status: "CONNECTED",
    webhookStatus: "VERIFIED",
    lastSyncAt: "2026-10-04T12:00:00Z",
    messagingLimitTier: "TIER_10K",
    dailyMessagesSentToday: 410,
    dailyMessagesLimit: 10000,
  },
];

export const DEMO_LEADS: Lead[] = [
  // Apex Healthcare Leads
  {
    id: "lead_101",
    businessId: "biz_apex_health",
    name: "Sunita Aggarwal",
    phone: "+91 98110 54321",
    email: "sunita.aggarwal@gmail.com",
    source: "WhatsApp Inbound",
    industry: "Orthopedics & Joint Replacement",
    requirement: "Knee replacement surgery consultation with Dr. Mehra",
    status: "quotation_sent",
    assignedToAgentId: "user_apex_agent",
    assignedToAgentName: "Priya Sharma",
    estimatedValue: 285000,
    tags: ["High Priority", "Knee Replacement", "Insurance Pre-Check"],
    lastContactAt: "2026-10-04T09:15:00Z",
    nextFollowUpAt: "2026-10-05T11:00:00Z",
    notes: "Patient shared MRI scans on WhatsApp. Insurance pre-authorization requested.",
    createdAt: "2026-10-02T14:20:00Z",
    updatedAt: "2026-10-04T09:15:00Z",
  },
  {
    id: "lead_102",
    businessId: "biz_apex_health",
    name: "Rajesh Malhotra",
    phone: "+91 98712 34567",
    email: "rmalhotra@techsolutions.com",
    source: "Website Form (WhatsApp sync)",
    industry: "Executive Health Checkup",
    requirement: "Comprehensive annual corporate executive checkup for 40 directors",
    status: "negotiation",
    assignedToAgentId: "user_apex_agent",
    assignedToAgentName: "Priya Sharma",
    estimatedValue: 420000,
    tags: ["Corporate B2B", "Executive Package", "40 PAX"],
    lastContactAt: "2026-10-03T16:40:00Z",
    nextFollowUpAt: "2026-10-05T15:30:00Z",
    notes: "Requested 10% corporate volume discount. Quotation revised.",
    createdAt: "2026-09-28T11:10:00Z",
    updatedAt: "2026-10-03T16:40:00Z",
  },
  {
    id: "lead_103",
    businessId: "biz_apex_health",
    name: "Deepak Rawat",
    phone: "+91 99100 88776",
    email: "deepak.rawat@outlook.com",
    source: "Google Maps 3-Pack",
    industry: "Cardiology & Diagnostics",
    requirement: "TMT + Echo cardiology screening after sudden fatigue",
    status: "contacted",
    assignedToAgentId: "user_apex_agent",
    assignedToAgentName: "Priya Sharma",
    estimatedValue: 12500,
    tags: ["Cardio", "Immediate Slot"],
    lastContactAt: "2026-10-04T11:00:00Z",
    nextFollowUpAt: "2026-10-04T16:00:00Z",
    notes: "Slot booked for tomorrow morning 9:00 AM fasting.",
    createdAt: "2026-10-04T08:30:00Z",
    updatedAt: "2026-10-04T11:00:00Z",
  },
  {
    id: "lead_104",
    businessId: "biz_apex_health",
    name: "Ananya Deshmukh",
    phone: "+91 98200 45678",
    email: "ananya.d@gmail.com",
    source: "Instagram Ad Click-to-WhatsApp",
    industry: "Maternity & Birthing Suite",
    requirement: "Luxury Birthing Suite package tour and obstetrician consult",
    status: "won",
    assignedToAgentId: "user_apex_agent",
    assignedToAgentName: "Priya Sharma",
    estimatedValue: 175000,
    tags: ["Maternity", "Deluxe Suite", "Confirmed"],
    lastContactAt: "2026-10-02T18:00:00Z",
    notes: "Advance booking deposit paid via WhatsApp link.",
    createdAt: "2026-09-20T10:00:00Z",
    updatedAt: "2026-10-02T18:00:00Z",
  },

  // UrbanNest Real Estate Leads
  {
    id: "lead_201",
    businessId: "biz_urbannest",
    name: "Aditya Khurana",
    phone: "+91 98118 76543",
    email: "aditya.k@venturecap.in",
    source: "WhatsApp Campaign Broadcast",
    industry: "Ultra-Luxury Residential",
    requirement: "4 BHK Penthouse in Sector 128 Noida Expressway (₹6 Cr+)",
    status: "negotiation",
    assignedToAgentId: "user_urbannest_owner",
    assignedToAgentName: "Vikram Singhania",
    estimatedValue: 65000000,
    tags: ["Penthouse", "HNIs", "Expressway Corridor"],
    lastContactAt: "2026-10-04T10:00:00Z",
    nextFollowUpAt: "2026-10-06T11:30:00Z",
    notes: "Site visit completed Saturday. Reviewing payment plan with bank.",
    createdAt: "2026-09-25T14:10:00Z",
    updatedAt: "2026-10-04T10:00:00Z",
  },
  {
    id: "lead_202",
    businessId: "biz_urbannest",
    name: "Meera Sen",
    phone: "+91 98733 22110",
    email: "meera.sen@interiors.co",
    source: "Google Ads Click-to-WhatsApp",
    industry: "Commercial Grade-A Office",
    requirement: "3,500 sq ft fitted office space in Sector 62 IT Park",
    status: "qualified",
    assignedToAgentId: "user_urbannest_owner",
    assignedToAgentName: "Vikram Singhania",
    estimatedValue: 38500000,
    tags: ["Commercial", "IT Park", "Ready Possession"],
    lastContactAt: "2026-10-03T15:20:00Z",
    nextFollowUpAt: "2026-10-05T14:00:00Z",
    notes: "Shared floor layout and parking allocation via WhatsApp doc.",
    createdAt: "2026-10-01T12:00:00Z",
    updatedAt: "2026-10-03T15:20:00Z",
  },
  {
    id: "lead_203",
    businessId: "biz_urbannest",
    name: "Harpreet Singh Bindra",
    phone: "+91 99119 33445",
    source: "Referral via Client",
    industry: "Luxury Villa",
    requirement: "Independent 500 sq yd villa in Greater Noida Pari Chowk",
    status: "new",
    estimatedValue: 42000000,
    tags: ["Villa", "Investor", "Cash Buyer"],
    lastContactAt: "2026-10-04T07:45:00Z",
    nextFollowUpAt: "2026-10-04T14:00:00Z",
    notes: "Inbound WhatsApp inquiry received from weekend referral.",
    createdAt: "2026-10-04T07:45:00Z",
    updatedAt: "2026-10-04T07:45:00Z",
  },
  {
    id: "lead_204",
    businessId: "biz_urbannest",
    name: "Sameer Nambiar",
    phone: "+91 98450 99887",
    email: "sameer.n@nambiartech.com",
    source: "WhatsApp Chatbot",
    industry: "3 BHK Apartment",
    requirement: "Ready to move 3 BHK under ₹1.8 Cr",
    status: "lost",
    estimatedValue: 18000000,
    tags: ["Budget Mismatch", "Noida Ext"],
    lastContactAt: "2026-09-30T17:00:00Z",
    notes: "Looking strictly under ₹1.2 Cr, outside our project portfolio.",
    createdAt: "2026-09-22T09:30:00Z",
    updatedAt: "2026-09-30T17:00:00Z",
  },

  // Nexora Tech Leads
  {
    id: "lead_301",
    businessId: "biz_nexora",
    name: "Rohan Varma (CTO)",
    phone: "+91 98109 11223",
    email: "rohan@finbridge.io",
    source: "Website Demo Request",
    industry: "Fintech Platform",
    requirement: "Enterprise API integration & automated compliance monitoring",
    status: "quotation_sent",
    assignedToAgentId: "user_nexora_owner",
    assignedToAgentName: "Kavita Rao",
    estimatedValue: 950000,
    tags: ["High Ticket", "Fintech", "SOC2"],
    lastContactAt: "2026-10-03T18:00:00Z",
    nextFollowUpAt: "2026-10-07T11:00:00Z",
    notes: "Sent proposal via WhatsApp. Awaiting legal approval from board.",
    createdAt: "2026-09-26T15:30:00Z",
    updatedAt: "2026-10-03T18:00:00Z",
  },
  {
    id: "lead_302",
    businessId: "biz_nexora",
    name: "Shreya Joshi",
    phone: "+91 98230 77665",
    email: "shreya@omnilogistics.in",
    source: "LinkedIn Click-to-WhatsApp",
    industry: "Logistics SaaS",
    requirement: "Cloud infrastructure migration from AWS to hybrid architecture",
    status: "won",
    assignedToAgentId: "user_nexora_owner",
    assignedToAgentName: "Kavita Rao",
    estimatedValue: 1450000,
    tags: ["Enterprise Cloud", "Signed"],
    lastContactAt: "2026-10-01T12:00:00Z",
    notes: "Contract signed and initial retainer received.",
    createdAt: "2026-09-15T10:00:00Z",
    updatedAt: "2026-10-01T12:00:00Z",
  },
  {
    id: "lead_303",
    businessId: "biz_nexora",
    name: "Tushar Bansal",
    phone: "+91 98710 66554",
    email: "tushar@retailflow.com",
    source: "WhatsApp Inbound",
    industry: "E-Commerce Infrastructure",
    requirement: "Kafka microservices architecture consulting",
    status: "contacted",
    assignedToAgentId: "user_nexora_owner",
    assignedToAgentName: "Kavita Rao",
    estimatedValue: 600000,
    tags: ["Architecture", "E-com"],
    lastContactAt: "2026-10-04T09:30:00Z",
    nextFollowUpAt: "2026-10-05T16:00:00Z",
    notes: "Introductory Zoom call scheduled via automated WhatsApp booking link.",
    createdAt: "2026-10-02T16:45:00Z",
    updatedAt: "2026-10-04T09:30:00Z",
  },

  // SpiceCraft Dining Leads
  {
    id: "lead_401",
    businessId: "biz_spicecraft",
    name: "Varun Narang",
    phone: "+91 98104 55667",
    email: "varun.narang@delhievents.com",
    source: "WhatsApp Keyword 'PARTY'",
    industry: "Corporate Gathering",
    requirement: "Private rooftop dining for 65 guests with bar & live grilling",
    status: "won",
    assignedToAgentId: "user_spicecraft_owner",
    assignedToAgentName: "Manish Kapoor",
    estimatedValue: 185000,
    tags: ["Private Rooftop", "65 PAX", "Advance Paid"],
    lastContactAt: "2026-10-03T20:00:00Z",
    notes: "Tasting session completed. Menu finalized and advance token processed.",
    createdAt: "2026-09-29T11:00:00Z",
    updatedAt: "2026-10-03T20:00:00Z",
  },
  {
    id: "lead_402",
    businessId: "biz_spicecraft",
    name: "Neha Sehgal",
    phone: "+91 98765 43210",
    source: "Instagram Click-to-WhatsApp",
    industry: "Wedding Anniversary",
    requirement: "Candlelight cabana setup for 2 with curated chef's menu",
    status: "quotation_sent",
    assignedToAgentId: "user_spicecraft_owner",
    assignedToAgentName: "Manish Kapoor",
    estimatedValue: 14500,
    tags: ["Cabana", "Couples", "Weekend"],
    lastContactAt: "2026-10-04T10:15:00Z",
    nextFollowUpAt: "2026-10-04T18:00:00Z",
    notes: "Sent anniversary menu options and floral add-on rates.",
    createdAt: "2026-10-03T14:30:00Z",
    updatedAt: "2026-10-04T10:15:00Z",
  },
  {
    id: "lead_403",
    businessId: "biz_spicecraft",
    name: "Amitabh Roy",
    phone: "+91 99102 33441",
    source: "Google Business Profile",
    industry: "Family Reunion",
    requirement: "Sunday brunch table for 18 people with kids play area access",
    status: "new",
    estimatedValue: 32000,
    tags: ["Family", "Brunch", "Sunday"],
    lastContactAt: "2026-10-04T11:20:00Z",
    nextFollowUpAt: "2026-10-04T15:00:00Z",
    notes: "Requested table in non-smoking air-conditioned zone.",
    createdAt: "2026-10-04T11:20:00Z",
    updatedAt: "2026-10-04T11:20:00Z",
  },

  // Velocita Motors Leads
  {
    id: "lead_501",
    businessId: "biz_velocita",
    name: "Gaurav Chawla",
    phone: "+91 98111 88990",
    email: "gchawla@apexglobal.in",
    source: "WhatsApp Campaign 'EV_LAUNCH'",
    industry: "Luxury Electric Sedan",
    requirement: "Home test drive and exchange evaluation for BMW i4 M50",
    status: "negotiation",
    assignedToAgentId: "user_velocita_owner",
    assignedToAgentName: "Rajat Verma",
    estimatedValue: 8200000,
    tags: ["BMW i4", "Exchange Bonus", "VIP Test Drive"],
    lastContactAt: "2026-10-04T11:30:00Z",
    nextFollowUpAt: "2026-10-05T12:00:00Z",
    notes: "Home test drive went great. Evaluating exchange price of 2021 Audi A6.",
    createdAt: "2026-09-27T10:15:00Z",
    updatedAt: "2026-10-04T11:30:00Z",
  },
  {
    id: "lead_502",
    businessId: "biz_velocita",
    name: "Prateek Mathur",
    phone: "+91 98730 11998",
    email: "pmathur@consultants.in",
    source: "Walk-in Showroom QR Scan",
    industry: "Certified Pre-Owned Luxury",
    requirement: "Mercedes-Benz E-Class 220d (under 30,000 km)",
    status: "won",
    assignedToAgentId: "user_velocita_owner",
    assignedToAgentName: "Rajat Verma",
    estimatedValue: 5400000,
    tags: ["Pre-Owned", "Mercedes E-Class", "Delivery Scheduled"],
    lastContactAt: "2026-10-02T16:00:00Z",
    notes: "Financing approved by HDFC Bank. Delivery set for Navratri auspicious day.",
    createdAt: "2026-09-18T14:00:00Z",
    updatedAt: "2026-10-02T16:00:00Z",
  },
  {
    id: "lead_503",
    businessId: "biz_velocita",
    name: "Siddharth Jain",
    phone: "+91 99105 44332",
    source: "Facebook Click-to-WhatsApp",
    industry: "Performance SUV",
    requirement: "Porsche Macan GTS custom spec configuration",
    status: "qualified",
    assignedToAgentId: "user_velocita_owner",
    assignedToAgentName: "Rajat Verma",
    estimatedValue: 11500000,
    tags: ["Porsche", "Custom Spec", "Ultra HNI"],
    lastContactAt: "2026-10-03T17:15:00Z",
    nextFollowUpAt: "2026-10-06T14:30:00Z",
    notes: "Sent Porsche code and carbon package breakdown over WhatsApp.",
    createdAt: "2026-10-01T15:00:00Z",
    updatedAt: "2026-10-03T17:15:00Z",
  },
  {
    id: "lead_504",
    businessId: "biz_velocita",
    name: "Karan Johar",
    phone: "+91 98201 11224",
    source: "WhatsApp Keyword 'SERVICE'",
    industry: "Periodic Service & Ceramic Coat",
    requirement: "Annual 30,000 km service + 9H ceramic coating for Range Rover Velar",
    status: "won",
    assignedToAgentId: "user_velocita_owner",
    assignedToAgentName: "Rajat Verma",
    estimatedValue: 165000,
    tags: ["Detailing", "Ceramic", "Service"],
    lastContactAt: "2026-10-04T08:00:00Z",
    notes: "Flatbed pickup scheduled from Gurgaon residence at 10:00 AM.",
    createdAt: "2026-10-03T11:00:00Z",
    updatedAt: "2026-10-04T08:00:00Z",
  },
  {
    id: "lead_505",
    businessId: "biz_velocita",
    name: "Manoj Tiwari",
    phone: "+91 98711 00998",
    source: "WhatsApp Inbound",
    industry: "Pre-Owned Hatchback",
    requirement: "Looking for budget car under ₹6 Lakh",
    status: "lost",
    estimatedValue: 600000,
    tags: ["Below Segment"],
    lastContactAt: "2026-09-29T10:00:00Z",
    notes: "We exclusively inventory luxury European marques starting ₹30 Lakh.",
    createdAt: "2026-09-29T09:30:00Z",
    updatedAt: "2026-09-29T10:00:00Z",
  },
];

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: "cust_101",
    businessId: "biz_apex_health",
    name: "Sunita Aggarwal",
    phone: "+91 98110 54321",
    email: "sunita.aggarwal@gmail.com",
    company: "Aggarwal Traders",
    totalOrdersOrDeals: 1,
    totalSpent: 285000,
    tags: ["Orthopedics", "Active Treatment"],
    notes: "Knee replacement surgery scheduled.",
    createdAt: "2026-10-02T14:20:00Z",
    lastActiveAt: "2026-10-04T09:15:00Z",
  },
  {
    id: "cust_102",
    businessId: "biz_apex_health",
    name: "Ananya Deshmukh",
    phone: "+91 98200 45678",
    email: "ananya.d@gmail.com",
    totalOrdersOrDeals: 2,
    totalSpent: 210000,
    tags: ["Maternity", "Deluxe Suite", "VIP"],
    notes: "Pre-natal visits ongoing smoothly.",
    createdAt: "2026-09-20T10:00:00Z",
    lastActiveAt: "2026-10-02T18:00:00Z",
  },
  {
    id: "cust_103",
    businessId: "biz_apex_health",
    name: "Col. Sanjeev Bakshi",
    phone: "+91 98115 66778",
    email: "col.bakshi@veterans.org",
    totalOrdersOrDeals: 4,
    totalSpent: 68000,
    tags: ["Cardio", "Regular Patient", "Senior Citizen"],
    notes: "Quarterly blood work and cardiologist checkup.",
    createdAt: "2026-04-10T11:00:00Z",
    lastActiveAt: "2026-10-01T15:00:00Z",
  },
  {
    id: "cust_104",
    businessId: "biz_apex_health",
    name: "Ritu Kapoor",
    phone: "+91 98711 88990",
    email: "ritu.kapoor@designhaus.in",
    totalOrdersOrDeals: 1,
    totalSpent: 45000,
    tags: ["Dermatology", "Cosmetology"],
    createdAt: "2026-08-15T12:00:00Z",
    lastActiveAt: "2026-09-28T16:30:00Z",
  },

  // UrbanNest Customers
  {
    id: "cust_201",
    businessId: "biz_urbannest",
    name: "Aditya Khurana",
    phone: "+91 98118 76543",
    email: "aditya.k@venturecap.in",
    company: "VentureCap India",
    totalOrdersOrDeals: 1,
    totalSpent: 65000000,
    tags: ["Penthouse", "HNIs"],
    createdAt: "2026-09-25T14:10:00Z",
    lastActiveAt: "2026-10-04T10:00:00Z",
  },
  {
    id: "cust_202",
    businessId: "biz_urbannest",
    name: "Ramanathan Iyer",
    phone: "+91 98450 11223",
    email: "r.iyer@fintechgroup.sg",
    company: "SingaFin Advisors",
    totalOrdersOrDeals: 2,
    totalSpent: 82000000,
    tags: ["NRI Investor", "Sector 128"],
    notes: "Purchased two luxury apartments in Tower A for rental yield.",
    createdAt: "2026-03-14T09:00:00Z",
    lastActiveAt: "2026-09-29T14:20:00Z",
  },
  {
    id: "cust_203",
    businessId: "biz_urbannest",
    name: "Komal Bajaj",
    phone: "+91 98210 99887",
    email: "komal@bajajauto.com",
    totalOrdersOrDeals: 1,
    totalSpent: 48000000,
    tags: ["4 BHK", "Golf Course View"],
    createdAt: "2026-06-20T16:00:00Z",
    lastActiveAt: "2026-09-15T11:00:00Z",
  },

  // Nexora Tech Customers
  {
    id: "cust_301",
    businessId: "biz_nexora",
    name: "Shreya Joshi",
    phone: "+91 98230 77665",
    email: "shreya@omnilogistics.in",
    company: "OmniLogistics India Pvt Ltd",
    totalOrdersOrDeals: 3,
    totalSpent: 2850000,
    tags: ["Enterprise SaaS", "Active Retainer"],
    createdAt: "2026-09-15T10:00:00Z",
    lastActiveAt: "2026-10-04T11:15:00Z",
  },
  {
    id: "cust_302",
    businessId: "biz_nexora",
    name: "Devendra Patil",
    phone: "+91 98900 12345",
    email: "devendra@cloudpay.co",
    company: "CloudPay Gateway",
    totalOrdersOrDeals: 2,
    totalSpent: 1600000,
    tags: ["Fintech", "Payment Engine"],
    createdAt: "2026-05-11T14:00:00Z",
    lastActiveAt: "2026-09-24T18:00:00Z",
  },

  // SpiceCraft Customers
  {
    id: "cust_401",
    businessId: "biz_spicecraft",
    name: "Varun Narang",
    phone: "+91 98104 55667",
    email: "varun.narang@delhievents.com",
    company: "Delhi Events Co",
    totalOrdersOrDeals: 5,
    totalSpent: 420000,
    tags: ["Corporate Host", "Rooftop VIP"],
    createdAt: "2026-04-12T10:00:00Z",
    lastActiveAt: "2026-10-03T20:00:00Z",
  },
  {
    id: "cust_402",
    businessId: "biz_spicecraft",
    name: "Divya Oberoi",
    phone: "+91 98111 22334",
    email: "divya.oberoi@gmail.com",
    totalOrdersOrDeals: 8,
    totalSpent: 84000,
    tags: ["Loyal Gourmet", "Brunch Regular"],
    createdAt: "2026-02-28T13:00:00Z",
    lastActiveAt: "2026-10-01T21:30:00Z",
  },

  // Velocita Motors Customers
  {
    id: "cust_501",
    businessId: "biz_velocita",
    name: "Prateek Mathur",
    phone: "+91 98730 11998",
    email: "pmathur@consultants.in",
    totalOrdersOrDeals: 1,
    totalSpent: 5400000,
    tags: ["Mercedes E-Class", "VIP Member"],
    createdAt: "2026-09-18T14:00:00Z",
    lastActiveAt: "2026-10-02T16:00:00Z",
  },
  {
    id: "cust_502",
    businessId: "biz_velocita",
    name: "Karan Johar",
    phone: "+91 98201 11224",
    totalOrdersOrDeals: 3,
    totalSpent: 385000,
    tags: ["Range Rover", "Ceramic Coating", "Service VIP"],
    createdAt: "2026-01-22T11:00:00Z",
    lastActiveAt: "2026-10-04T08:00:00Z",
  },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: "conv_101",
    businessId: "biz_apex_health",
    customerId: "cust_101",
    customerName: "Sunita Aggarwal",
    customerPhone: "+91 98110 54321",
    lastMessage: "I have shared the insurance policy copy. Will cashless be accepted?",
    lastMessageAt: "2026-10-04T09:15:00Z",
    lastMessageSender: "customer",
    unreadCount: 1,
    status: "open",
    assignedAgentId: "user_apex_agent",
    assignedAgentName: "Priya Sharma",
    leadStatus: "quotation_sent",
    tags: ["Orthopedics", "Insurance Check"],
    notesCount: 2,
    createdAt: "2026-10-02T14:20:00Z",
  },
  {
    id: "conv_102",
    businessId: "biz_apex_health",
    customerId: "cust_102",
    customerName: "Ananya Deshmukh",
    customerPhone: "+91 98200 45678",
    lastMessage: "Your appointment with Dr. Shalini is confirmed for Tuesday 10:30 AM.",
    lastMessageAt: "2026-10-02T18:00:00Z",
    lastMessageSender: "bot",
    unreadCount: 0,
    status: "closed",
    assignedAgentId: "user_apex_agent",
    assignedAgentName: "Priya Sharma",
    leadStatus: "won",
    tags: ["Maternity", "Confirmed"],
    notesCount: 1,
    createdAt: "2026-09-20T10:00:00Z",
  },
  {
    id: "conv_201",
    businessId: "biz_urbannest",
    customerId: "cust_201",
    customerName: "Aditya Khurana",
    customerPhone: "+91 98118 76543",
    lastMessage: "Can we schedule a call with the architect regarding the terrace pool?",
    lastMessageAt: "2026-10-04T10:00:00Z",
    lastMessageSender: "customer",
    unreadCount: 1,
    status: "assigned",
    assignedAgentId: "user_urbannest_owner",
    assignedAgentName: "Vikram Singhania",
    leadStatus: "negotiation",
    tags: ["Penthouse", "HNIs", "High Priority"],
    notesCount: 3,
    createdAt: "2026-09-25T14:10:00Z",
  },
  {
    id: "conv_202",
    businessId: "biz_urbannest",
    customerId: "cust_202",
    customerName: "Ramanathan Iyer",
    customerPhone: "+91 98450 11223",
    lastMessage: "Received the rental agreement draft. Looks completely fine.",
    lastMessageAt: "2026-09-29T14:20:00Z",
    lastMessageSender: "customer",
    unreadCount: 0,
    status: "follow_up",
    assignedAgentId: "user_urbannest_owner",
    assignedAgentName: "Vikram Singhania",
    leadStatus: "won",
    tags: ["NRI Investor"],
    notesCount: 1,
    createdAt: "2026-03-14T09:00:00Z",
  },
  {
    id: "conv_301",
    businessId: "biz_nexora",
    customerId: "cust_301",
    customerName: "Shreya Joshi",
    customerPhone: "+91 98230 77665",
    lastMessage: "Sprint 3 deliverables have been deployed to staging. Testing link enclosed.",
    lastMessageAt: "2026-10-04T11:15:00Z",
    lastMessageSender: "business",
    unreadCount: 0,
    status: "open",
    assignedAgentId: "user_nexora_owner",
    assignedAgentName: "Kavita Rao",
    leadStatus: "won",
    tags: ["Enterprise Retainer", "Active Sprint"],
    notesCount: 4,
    createdAt: "2026-09-15T10:00:00Z",
  },
  {
    id: "conv_401",
    businessId: "biz_spicecraft",
    customerId: "cust_401",
    customerName: "Varun Narang",
    customerPhone: "+91 98104 55667",
    lastMessage: "DJ setup and bar permits are in place for Friday evening. See you at 7 PM!",
    lastMessageAt: "2026-10-03T20:00:00Z",
    lastMessageSender: "business",
    unreadCount: 0,
    status: "closed",
    assignedAgentId: "user_spicecraft_owner",
    assignedAgentName: "Manish Kapoor",
    leadStatus: "won",
    tags: ["Rooftop", "Corporate 65 PAX"],
    notesCount: 2,
    createdAt: "2026-04-12T10:00:00Z",
  },
  {
    id: "conv_501",
    businessId: "biz_velocita",
    customerId: "cust_501",
    customerName: "Prateek Mathur",
    customerPhone: "+91 98730 11998",
    lastMessage: "The RTO registration number has been allotted: UP 16 DX 0077.",
    lastMessageAt: "2026-10-02T16:00:00Z",
    lastMessageSender: "business",
    unreadCount: 0,
    status: "closed",
    assignedAgentId: "user_velocita_owner",
    assignedAgentName: "Rajat Verma",
    leadStatus: "won",
    tags: ["Mercedes E-Class"],
    notesCount: 2,
    createdAt: "2026-09-18T14:00:00Z",
  },
  {
    id: "conv_502",
    businessId: "biz_velocita",
    customerId: "cust_502",
    customerName: "Karan Johar",
    customerPhone: "+91 98201 11224",
    lastMessage: "Driver has reached with the flatbed. Vehicle being loaded safely.",
    lastMessageAt: "2026-10-04T08:00:00Z",
    lastMessageSender: "bot",
    unreadCount: 0,
    status: "open",
    assignedAgentId: "user_velocita_owner",
    assignedAgentName: "Rajat Verma",
    leadStatus: "won",
    tags: ["Service", "Range Rover"],
    notesCount: 1,
    createdAt: "2026-01-22T11:00:00Z",
  },
];

export const DEMO_MESSAGES: Record<string, ChatMessage[]> = {
  conv_101: [
    {
      id: "msg_101_1",
      conversationId: "conv_101",
      businessId: "biz_apex_health",
      sender: "customer",
      text: "Namaste. I want to inquire about Dr. Arun Mehra's consultation for knee replacement surgery for my mother.",
      timestamp: "2026-10-02T14:20:00Z",
      status: "read",
    },
    {
      id: "msg_101_2",
      conversationId: "conv_101",
      businessId: "biz_apex_health",
      sender: "bot",
      text: "Welcome to Apex Super-Speciality Hospital! 🏥 Dr. Arun Mehra is available Mon-Sat 10:00 AM to 2:00 PM. Would you like to book an appointment or share previous knee X-Ray/MRI reports?",
      timestamp: "2026-10-02T14:20:15Z",
      status: "read",
    },
    {
      id: "msg_101_3",
      conversationId: "conv_101",
      businessId: "biz_apex_health",
      sender: "customer",
      text: "I have uploaded the reports. Please let me know the estimated package cost and if Star Health insurance is accepted.",
      timestamp: "2026-10-02T14:24:00Z",
      status: "read",
    },
    {
      id: "msg_101_4",
      conversationId: "conv_101",
      businessId: "biz_apex_health",
      sender: "agent",
      senderName: "Priya Sharma",
      text: "Hello Sunita ji! Priya from Apex Patient Care desk here. Yes, Star Health Insurance is 100% cashless at our hospital. The bilateral knee package is ₹2,85,000 all-inclusive.",
      timestamp: "2026-10-02T14:35:00Z",
      status: "read",
    },
    {
      id: "msg_101_5",
      conversationId: "conv_101",
      businessId: "biz_apex_health",
      sender: "customer",
      text: "I have shared the insurance policy copy. Will cashless be accepted?",
      timestamp: "2026-10-04T09:15:00Z",
      status: "delivered",
    },
  ],
  conv_201: [
    {
      id: "msg_201_1",
      conversationId: "conv_201",
      businessId: "biz_urbannest",
      sender: "customer",
      text: "Hello Vikram, saw the brochure for the Golf Vista Penthouse. Is the private splash pool temperature controlled?",
      timestamp: "2026-10-03T16:30:00Z",
      status: "read",
    },
    {
      id: "msg_201_2",
      conversationId: "conv_201",
      businessId: "biz_urbannest",
      sender: "agent",
      senderName: "Vikram Singhania",
      text: "Good afternoon Aditya ji! Yes, the 4 BHK Sky Penthouse features a climate-controlled infinity deck pool with Spanish filtration, offering panoramic views of the Jaypee Greens championship course.",
      timestamp: "2026-10-03T16:38:00Z",
      status: "read",
    },
    {
      id: "msg_201_3",
      conversationId: "conv_201",
      businessId: "biz_urbannest",
      sender: "customer",
      text: "Can we schedule a call with the architect regarding the terrace pool?",
      timestamp: "2026-10-04T10:00:00Z",
      status: "read",
    },
  ],
};

export const DEMO_TEMPLATES: MessageTemplate[] = [
  {
    id: "tpl_appointment_confirm",
    businessId: "biz_apex_health",
    name: "appointment_confirmation_v1",
    category: "UTILITY",
    language: "en_US",
    status: "APPROVED",
    headerType: "TEXT",
    headerText: "Appointment Confirmed 🏥",
    body: "Hello {{customer_name}}, your appointment with {{doctor_name}} at {{hospital_name}} is confirmed for {{appointment_date}} at {{appointment_time}}. Please arrive 15 minutes early with past medical records.",
    footer: "Apex Super-Speciality Hospital | 24/7 Helpline",
    buttons: [
      { type: "URL", text: "Get Directions", value: "https://maps.google.com" },
      { type: "PHONE_NUMBER", text: "Emergency Desk", value: "+919810123456" },
      { type: "QUICK_REPLY", text: "Reschedule" },
    ],
    variables: ["customer_name", "doctor_name", "hospital_name", "appointment_date", "appointment_time"],
    createdAt: "2026-02-18T10:00:00Z",
    metaTemplateId: "meta_tpl_9871239812",
  },
  {
    id: "tpl_property_invitation",
    businessId: "biz_urbannest",
    name: "luxury_showcase_invite_v2",
    category: "MARKETING",
    language: "en_US",
    status: "APPROVED",
    headerType: "IMAGE",
    body: "Dear {{customer_name}}, UrbanNest cordially invites you to the exclusive private viewing of {{project_name}} on the Noida Expressway this weekend. Discover ultra-luxury residences curated for leaders.",
    footer: "RERA Reg. UPRERAPRJ998812",
    buttons: [
      { type: "QUICK_REPLY", text: "Book Private Tour" },
      { type: "QUICK_REPLY", text: "Download Floorplans" },
    ],
    variables: ["customer_name", "project_name"],
    createdAt: "2026-02-22T14:30:00Z",
    metaTemplateId: "meta_tpl_4819203948",
  },
  {
    id: "tpl_lead_intake_welcome",
    businessId: "biz_nexora",
    name: "b2b_inbound_acknowledgement",
    category: "UTILITY",
    language: "en_US",
    status: "APPROVED",
    headerType: "TEXT",
    headerText: "Nexora Tech — Request Received",
    body: "Hi {{customer_name}}, thank you for reaching out to Nexora Cloud. Our senior solution architect {{agent_name}} has received your inquiry for {{service_name}} and will connect within 30 minutes.",
    footer: "Secure B2B Solutions",
    buttons: [
      { type: "URL", text: "View Case Studies", value: "https://nexoratech.io/case-studies" },
    ],
    variables: ["customer_name", "agent_name", "service_name"],
    createdAt: "2026-03-06T11:00:00Z",
    metaTemplateId: "meta_tpl_1928374650",
  },
  {
    id: "tpl_table_booking_alert",
    businessId: "biz_spicecraft",
    name: "reservation_booking_confirmed",
    category: "UTILITY",
    language: "en_US",
    status: "APPROVED",
    headerType: "TEXT",
    headerText: "Table Reserved! 🍽️",
    body: "Hello {{customer_name}}, your table reservation for {{party_size}} guests at SpiceCraft CP is confirmed for {{booking_time}} on {{booking_date}}. We look forward to hosting you!",
    footer: "SpiceCraft Dining Group | Valet Available",
    buttons: [
      { type: "URL", text: "View Menu", value: "https://spicecraftdining.com/menu" },
      { type: "QUICK_REPLY", text: "Cancel Booking" },
    ],
    variables: ["customer_name", "party_size", "booking_time", "booking_date"],
    createdAt: "2026-03-14T09:20:00Z",
    metaTemplateId: "meta_tpl_5647382910",
  },
  {
    id: "tpl_vehicle_service_due",
    businessId: "biz_velocita",
    name: "annual_service_reminder_v1",
    category: "MARKETING",
    language: "en_US",
    status: "APPROVED",
    headerType: "TEXT",
    headerText: "Velocita VIP Service Desk 🏎️",
    body: "Greetings {{customer_name}}, your {{vehicle_model}} (Reg: {{reg_number}}) is due for its periodic maintenance inspection. Book this week to receive complimentary 32-point computer diagnostics and ceramic wash.",
    footer: "Authorized Luxury Service Center",
    buttons: [
      { type: "QUICK_REPLY", text: "Book Home Pickup" },
      { type: "PHONE_NUMBER", text: "Call Service Desk", value: "+919899044556" },
    ],
    variables: ["customer_name", "vehicle_model", "reg_number"],
    createdAt: "2026-03-20T12:00:00Z",
    metaTemplateId: "meta_tpl_8273645192",
  },
  {
    id: "tpl_google_review_request",
    businessId: "biz_apex_health",
    name: "patient_feedback_google_review",
    category: "UTILITY",
    language: "en_US",
    status: "APPROVED",
    headerType: "NONE",
    body: "Hi {{customer_name}}, thank you for choosing {{business_name}}! How was your experience today with our medical team? Please take 30 seconds to share your feedback.",
    footer: "Your feedback helps other patients",
    buttons: [
      { type: "URL", text: "⭐ Share Google Review", value: "https://digitalfx.in/review" },
      { type: "QUICK_REPLY", text: "Speak to Grievance Desk" },
    ],
    variables: ["customer_name", "business_name"],
    createdAt: "2026-03-22T15:00:00Z",
    metaTemplateId: "meta_tpl_3948572019",
  },
];

export const DEMO_AUTOMATIONS: Automation[] = [
  {
    id: "auto_101",
    businessId: "biz_apex_health",
    name: "Doctor Consultation Inbound Intake Bot",
    description: "Greets patient, identifies specialty requirement, captures medical records and routes lead to doctor desk.",
    trigger: "new_whatsapp_message",
    triggerConfig: { matchType: "all_incoming" },
    isActive: true,
    totalRuns: 1840,
    successRuns: 1792,
    failedRuns: 48,
    steps: [
      {
        id: "step_1",
        type: "trigger",
        actionType: "new_whatsapp_message",
        title: "Patient Sends WhatsApp Message",
        config: {},
        nextStepId: "step_2",
      },
      {
        id: "step_2",
        type: "action",
        actionType: "send_whatsapp_message",
        title: "Send Instant Hospital Greeting",
        config: {
          message: "Welcome to Apex Super-Speciality Hospital! 🏥 Please select the doctor department you need:\n1. Orthopedics & Joint Care\n2. Cardiology\n3. Gynecology & Maternity\n4. General Physician",
        },
        nextStepId: "step_3",
      },
      {
        id: "step_3",
        type: "condition",
        actionType: "condition",
        title: "Check Selected Specialty",
        config: { field: "message_text", containsAny: ["1", "ortho", "joint", "knee"] },
        nextStepId: "step_4",
      },
      {
        id: "step_4",
        type: "action",
        actionType: "add_tag",
        title: "Tag as Ortho Lead",
        config: { tag: "Orthopedics Inbound" },
        nextStepId: "step_5",
      },
      {
        id: "step_5",
        type: "action",
        actionType: "assign_agent",
        title: "Assign to Priya Sharma (Ortho Desk)",
        config: { agentId: "user_apex_agent" },
        nextStepId: "step_6",
      },
      {
        id: "step_6",
        type: "action",
        actionType: "create_followup",
        title: "Schedule Consultation Follow-up",
        config: { delayHours: 4, notes: "Verify patient insurance and slot booking" },
      },
    ],
    createdAt: "2026-02-25T11:00:00Z",
    updatedAt: "2026-10-01T14:00:00Z",
  },
  {
    id: "auto_201",
    businessId: "biz_urbannest",
    name: "Luxury Penthouse Brochure Auto-Dispenser",
    description: "Keywords 'PENTHOUSE', 'BROCHURE' trigger instant PDF floorplan delivery and lead capture.",
    trigger: "keyword",
    triggerConfig: { keywords: ["penthouse", "brochure", "price", "villa"] },
    isActive: true,
    totalRuns: 642,
    successRuns: 635,
    failedRuns: 7,
    steps: [
      {
        id: "step_1",
        type: "trigger",
        actionType: "keyword",
        title: "Keyword 'PENTHOUSE' detected",
        config: { keywords: ["penthouse", "brochure"] },
        nextStepId: "step_2",
      },
      {
        id: "step_2",
        type: "action",
        actionType: "send_template",
        title: "Send WhatsApp Luxury Invitation",
        config: { templateId: "tpl_property_invitation" },
        nextStepId: "step_3",
      },
      {
        id: "step_3",
        type: "action",
        actionType: "create_lead",
        title: "Add to High-Value Pipeline",
        config: { estimatedValue: 50000000, status: "new" },
        nextStepId: "step_4",
      },
      {
        id: "step_4",
        type: "action",
        actionType: "notify_admin",
        title: "SMS/App Alert to Vikram Singhania",
        config: { recipient: "+919871155443" },
      },
    ],
    createdAt: "2026-03-01T15:00:00Z",
    updatedAt: "2026-09-28T10:00:00Z",
  },
  {
    id: "auto_301",
    businessId: "biz_nexora",
    name: "API Inbound Lead Instant SLA Router",
    description: "Routes website demo requests to sales engineer within 60 seconds with calendar link.",
    trigger: "new_lead",
    triggerConfig: { source: "Website Demo" },
    isActive: true,
    totalRuns: 310,
    successRuns: 308,
    failedRuns: 2,
    steps: [
      {
        id: "step_1",
        type: "trigger",
        actionType: "new_lead",
        title: "New Lead Generated from Web Demo",
        config: {},
        nextStepId: "step_2",
      },
      {
        id: "step_2",
        type: "action",
        actionType: "send_template",
        title: "Send Official SLA Acknowledgement",
        config: { templateId: "tpl_lead_intake_welcome" },
      },
    ],
    createdAt: "2026-03-10T12:00:00Z",
    updatedAt: "2026-09-30T16:00:00Z",
  },
];

export const DEMO_CAMPAIGNS: Campaign[] = [
  {
    id: "camp_101",
    businessId: "biz_apex_health",
    name: "World Heart Day Free Echo & Cardio Camp",
    templateId: "tpl_appointment_confirm",
    templateName: "appointment_confirmation_v1",
    targetAudience: "All Past OPD Patients (Age 45+)",
    recipientCount: 1250,
    status: "completed",
    sentCount: 1250,
    deliveredCount: 1215,
    readCount: 940,
    failedCount: 35,
    repliesCount: 312,
    variables: { hospital_name: "Apex Super-Speciality Hospital", appointment_date: "Sunday 28th" },
    createdAt: "2026-09-24T09:00:00Z",
    startedAt: "2026-09-26T10:00:00Z",
    completedAt: "2026-09-26T10:35:00Z",
  },
  {
    id: "camp_201",
    businessId: "biz_urbannest",
    name: "Exclusive Preview: Golf Vista Penthouse Phase II",
    templateId: "tpl_property_invitation",
    templateName: "luxury_showcase_invite_v2",
    targetAudience: "Verified HNI Investors (Budget ₹5 Cr+)",
    recipientCount: 450,
    status: "running",
    sentCount: 450,
    deliveredCount: 432,
    readCount: 388,
    failedCount: 18,
    repliesCount: 94,
    variables: { project_name: "The Grand Sky Penthouses" },
    createdAt: "2026-10-02T14:00:00Z",
    startedAt: "2026-10-04T10:00:00Z",
  },
  {
    id: "camp_501",
    businessId: "biz_velocita",
    name: "Pre-Festive Ceramic Coating & Winter Maintenance",
    templateId: "tpl_vehicle_service_due",
    templateName: "annual_service_reminder_v1",
    targetAudience: "Luxury Vehicle Owners (Service Due)",
    recipientCount: 320,
    status: "scheduled",
    scheduledFor: "2026-10-08T10:00:00Z",
    sentCount: 0,
    deliveredCount: 0,
    readCount: 0,
    failedCount: 0,
    repliesCount: 0,
    variables: {},
    createdAt: "2026-10-03T16:00:00Z",
  },
];

export const DEMO_FOLLOWUPS: Followup[] = [
  {
    id: "fol_101",
    businessId: "biz_apex_health",
    customerName: "Sunita Aggarwal",
    customerPhone: "+91 98110 54321",
    leadId: "lead_101",
    dueAt: "2026-10-05T11:00:00Z",
    notes: "Follow up with Star Health insurance TPA desk for knee surgery cashless pre-approval letter.",
    assignedAgentName: "Priya Sharma",
    status: "pending",
    createdAt: "2026-10-04T09:15:00Z",
  },
  {
    id: "fol_201",
    businessId: "biz_urbannest",
    customerName: "Aditya Khurana",
    customerPhone: "+91 98118 76543",
    leadId: "lead_201",
    dueAt: "2026-10-06T11:30:00Z",
    notes: "Coordinate architect meeting for private pool structural drawings and payment installment schedule.",
    assignedAgentName: "Vikram Singhania",
    status: "pending",
    createdAt: "2026-10-04T10:00:00Z",
  },
  {
    id: "fol_301",
    businessId: "biz_nexora",
    customerName: "Rohan Varma",
    customerPhone: "+91 98109 11223",
    leadId: "lead_301",
    dueAt: "2026-10-07T11:00:00Z",
    notes: "Check if board ratified the compliance contract.",
    assignedAgentName: "Kavita Rao",
    status: "pending",
    createdAt: "2026-10-03T18:00:00Z",
  },
];

export const DEMO_TEAM_MEMBERS: TeamMember[] = [
  {
    id: "team_apex_1",
    businessId: "biz_apex_health",
    name: "Dr. Arun Mehra",
    email: "dr.arun@apexhealthcare.in",
    phone: "+91 98101 23456",
    role: "owner",
    status: "active",
    assignedConversationsCount: 5,
    joinedAt: "2026-02-15T11:00:00Z",
  },
  {
    id: "team_apex_2",
    businessId: "biz_apex_health",
    name: "Priya Sharma",
    email: "priya.frontdesk@apexhealthcare.in",
    phone: "+91 98101 77889",
    role: "agent",
    status: "active",
    assignedConversationsCount: 18,
    joinedAt: "2026-03-01T09:00:00Z",
  },
  {
    id: "team_apex_3",
    businessId: "biz_apex_health",
    name: "Dr. Shalini Gupta",
    email: "shalini.g@apexhealthcare.in",
    role: "manager",
    status: "active",
    assignedConversationsCount: 8,
    joinedAt: "2026-03-10T10:00:00Z",
  },
  {
    id: "team_urban_1",
    businessId: "biz_urbannest",
    name: "Vikram Singhania",
    email: "vikram@urbannestrealty.com",
    phone: "+91 98711 55443",
    role: "owner",
    status: "active",
    assignedConversationsCount: 12,
    joinedAt: "2026-02-20T14:00:00Z",
  },
];

export const DEMO_USAGE: UsageRecord[] = [
  {
    businessId: "biz_apex_health",
    month: "2026-10",
    messagesSent: 42150,
    messagesDelivered: 41600,
    messagesFailed: 550,
    contactsTotal: 18450,
    automationsActive: 8,
    campaignsRun: 4,
    teamMembersCount: 6,
    apiRequests: 84200,
    updatedAt: "2026-10-04T12:00:00Z",
  },
  {
    businessId: "biz_urbannest",
    month: "2026-10",
    messagesSent: 28400,
    messagesDelivered: 27950,
    messagesFailed: 450,
    contactsTotal: 12200,
    automationsActive: 6,
    campaignsRun: 3,
    teamMembersCount: 4,
    apiRequests: 49800,
    updatedAt: "2026-10-04T12:00:00Z",
  },
  {
    businessId: "biz_nexora",
    month: "2026-10",
    messagesSent: 8200,
    messagesDelivered: 8120,
    messagesFailed: 80,
    contactsTotal: 3450,
    automationsActive: 4,
    campaignsRun: 1,
    teamMembersCount: 3,
    apiRequests: 18200,
    updatedAt: "2026-10-04T12:00:00Z",
  },
  {
    businessId: "biz_spicecraft",
    month: "2026-10",
    messagesSent: 1890,
    messagesDelivered: 1840,
    messagesFailed: 50,
    contactsTotal: 890,
    automationsActive: 2,
    campaignsRun: 1,
    teamMembersCount: 2,
    apiRequests: 4200,
    updatedAt: "2026-10-04T12:00:00Z",
  },
  {
    businessId: "biz_velocita",
    month: "2026-10",
    messagesSent: 14500,
    messagesDelivered: 14280,
    messagesFailed: 220,
    contactsTotal: 6800,
    automationsActive: 5,
    campaignsRun: 2,
    teamMembersCount: 4,
    apiRequests: 31200,
    updatedAt: "2026-10-04T12:00:00Z",
  },
];

export const DEMO_INVOICES: Invoice[] = [
  {
    id: "inv_2026_0901",
    businessId: "biz_apex_health",
    businessName: "Apex Super-Speciality Hospital",
    amount: 24999,
    currency: "INR",
    status: "paid",
    planName: "Enterprise Tier",
    date: "2026-09-01T00:00:00Z",
    dueDate: "2026-09-05T00:00:00Z",
    paymentMethod: "Net Banking (HDFC)",
  },
  {
    id: "inv_2026_0902",
    businessId: "biz_urbannest",
    businessName: "UrbanNest Luxury Real Estate",
    amount: 9999,
    currency: "INR",
    status: "paid",
    planName: "Business Pro Tier",
    date: "2026-09-01T00:00:00Z",
    dueDate: "2026-09-05T00:00:00Z",
    paymentMethod: "Corporate Credit Card",
  },
  {
    id: "inv_2026_0903",
    businessId: "biz_nexora",
    businessName: "Nexora Cloud Technologies",
    amount: 4999,
    currency: "INR",
    status: "paid",
    planName: "Growth Tier",
    date: "2026-09-01T00:00:00Z",
    dueDate: "2026-09-05T00:00:00Z",
    paymentMethod: "UPI / Razorpay",
  },
  {
    id: "inv_2026_1001",
    businessId: "biz_apex_health",
    businessName: "Apex Super-Speciality Hospital",
    amount: 24999,
    currency: "INR",
    status: "paid",
    planName: "Enterprise Tier",
    date: "2026-10-01T00:00:00Z",
    dueDate: "2026-10-05T00:00:00Z",
    paymentMethod: "Net Banking (HDFC)",
  },
  {
    id: "inv_2026_1002",
    businessId: "biz_urbannest",
    businessName: "UrbanNest Luxury Real Estate",
    amount: 9999,
    currency: "INR",
    status: "paid",
    planName: "Business Pro Tier",
    date: "2026-10-01T00:00:00Z",
    dueDate: "2026-10-05T00:00:00Z",
    paymentMethod: "Corporate Credit Card",
  },
];

export const DEMO_PAYMENTS: PaymentTransaction[] = [
  {
    id: "pay_txn_89102",
    businessId: "biz_apex_health",
    businessName: "Apex Super-Speciality Hospital",
    amount: 24999,
    currency: "INR",
    gateway: "PayU",
    gatewayTransactionId: "PAYU_APEX_20261001_8912",
    status: "SUCCESS",
    createdAt: "2026-10-01T04:30:00Z",
  },
  {
    id: "pay_txn_89103",
    businessId: "biz_urbannest",
    businessName: "UrbanNest Luxury Real Estate",
    amount: 9999,
    currency: "INR",
    gateway: "PayU",
    gatewayTransactionId: "PAYU_URBAN_20261001_3491",
    status: "SUCCESS",
    createdAt: "2026-10-01T06:15:00Z",
  },
  {
    id: "pay_txn_89104",
    businessId: "biz_velocita",
    businessName: "Velocita Premium Motors",
    amount: 9999,
    currency: "INR",
    gateway: "PayU",
    gatewayTransactionId: "PAYU_VELO_20261001_7721",
    status: "SUCCESS",
    createdAt: "2026-10-01T08:45:00Z",
  },
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: "audit_1",
    timestamp: "2026-10-04T12:35:00Z",
    actorEmail: "yshashank513@gmail.com",
    actorRole: "super_admin",
    businessName: "Platform System",
    action: "SYSTEM_HEALTH_CHECK",
    ipAddress: "103.21.144.12",
    details: "Automated WhatsApp webhook health check verified 5 WABA endpoints (Status: 200 OK).",
  },
  {
    id: "audit_2",
    timestamp: "2026-10-04T11:45:00Z",
    actorEmail: "vikram@urbannestrealty.com",
    actorRole: "owner",
    businessId: "biz_urbannest",
    businessName: "UrbanNest Luxury Real Estate",
    action: "CAMPAIGN_LAUNCH",
    ipAddress: "122.176.48.91",
    details: "Launched campaign 'The Grand Sky Penthouses' to 450 verified VIP contacts.",
  },
  {
    id: "audit_3",
    timestamp: "2026-10-04T10:15:00Z",
    actorEmail: "dr.arun@apexhealthcare.in",
    actorRole: "owner",
    businessId: "biz_apex_health",
    businessName: "Apex Super-Speciality Hospital",
    action: "TEMPLATE_SUBMISSION",
    ipAddress: "115.114.92.10",
    details: "Submitted new WhatsApp Template 'patient_feedback_google_review' for Meta Cloud verification.",
  },
  {
    id: "audit_4",
    timestamp: "2026-10-04T09:30:00Z",
    actorEmail: "yshashank513@gmail.com",
    actorRole: "super_admin",
    businessId: "biz_velocita",
    businessName: "Velocita Premium Motors",
    action: "PLAN_UPGRADE",
    ipAddress: "103.21.144.12",
    details: "Extended high-throughput messaging tier to TIER_10K for festival sales.",
  },
];

export const DEMO_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: "tkt_801",
    businessId: "biz_spicecraft",
    businessName: "SpiceCraft Gourmet Dining Group",
    subject: "Requesting phone number migration to new SIM for Connaught Place branch",
    category: "WhatsApp API",
    priority: "HIGH",
    status: "IN_PROGRESS",
    createdAt: "2026-10-03T14:00:00Z",
    lastReplyAt: "2026-10-04T09:30:00Z",
    messagesCount: 4,
  },
  {
    id: "tkt_802",
    businessId: "biz_apex_health",
    businessName: "Apex Super-Speciality Hospital",
    subject: "Assistance configuring webhook for HIS (Hospital Information System) HL7 sync",
    category: "Automations",
    priority: "MEDIUM",
    status: "RESOLVED",
    createdAt: "2026-09-28T10:00:00Z",
    lastReplyAt: "2026-09-30T16:00:00Z",
    messagesCount: 6,
  },
  {
    id: "tkt_803",
    businessId: "biz_urbannest",
    businessName: "UrbanNest Luxury Real Estate",
    subject: "Inquiry on expanding messaging tier from Tier 10K to Tier 100K for Diwali",
    category: "Billing",
    priority: "LOW",
    status: "OPEN",
    createdAt: "2026-10-04T08:15:00Z",
    lastReplyAt: "2026-10-04T08:15:00Z",
    messagesCount: 1,
  },
];

// Aliases for unified consumption across store and client pages
export const INITIAL_PLANS = SAAS_PLANS;
export const INITIAL_BUSINESSES = DEMO_BUSINESSES;
export const INITIAL_WHATSAPP_ACCOUNTS = DEMO_WHATSAPP_ACCOUNTS;
export const INITIAL_LEADS = DEMO_LEADS;
export const INITIAL_CUSTOMERS = DEMO_CUSTOMERS;
export const INITIAL_CONVERSATIONS = DEMO_CONVERSATIONS;
export const INITIAL_MESSAGES: ChatMessage[] = Object.values(DEMO_MESSAGES).flat();
export const INITIAL_TEMPLATES = DEMO_TEMPLATES;
export const INITIAL_AUTOMATIONS = DEMO_AUTOMATIONS;
export const INITIAL_CAMPAIGNS = DEMO_CAMPAIGNS;
export const INITIAL_FOLLOWUPS = DEMO_FOLLOWUPS;
export const INITIAL_TEAM_MEMBERS = DEMO_TEAM_MEMBERS;
export const INITIAL_USAGE = DEMO_USAGE;
export const INITIAL_INVOICES = DEMO_INVOICES;
export const INITIAL_PAYMENTS = DEMO_PAYMENTS;
export const INITIAL_AUDIT_LOGS = DEMO_AUDIT_LOGS;
export const INITIAL_SUPPORT_TICKETS = DEMO_SUPPORT_TICKETS;

